In [1]:
import numpy as np

# Input and Output Data
X = np.array([[2, 9], [1, 5], [3, 6]], dtype=float)
y = np.array([[92], [86], [89]], dtype=float)

# Normalize input and output
X = X / np.amax(X, axis=0)  # Normalizing features
y = y / 100  # Normalizing output (since output is percentage-based)

# Sigmoid Function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Derivative of Sigmoid
def derivatives_sigmoid(x):
    return x * (1 - x)

# Hyperparameters
epoch = 5  # Number of training iterations
lr = 0.1   # Learning rate

# Network architecture
inputlayer_neurons = X.shape[1]       # 2 input features
hiddenlayer_neurons = 3               # Number of hidden layer neurons
output_neurons = 1                    # Output layer has 1 neuron

# Weight and bias initialization
wh = np.random.uniform(size=(inputlayer_neurons, hiddenlayer_neurons))  # Weights for input to hidden
bh = np.random.uniform(size=(1, hiddenlayer_neurons))                   # Bias for hidden layer
wout = np.random.uniform(size=(hiddenlayer_neurons, output_neurons))    # Weights for hidden to output
bout = np.random.uniform(size=(1, output_neurons))                      # Bias for output layer

# Training process
for i in range(epoch):
    # --- Forward Propagation ---
    hinp1 = np.dot(X, wh) + bh
    hlayer_act = sigmoid(hinp1)

    outinp1 = np.dot(hlayer_act, wout) + bout
    output = sigmoid(outinp1)

    # --- Backpropagation ---
    EO = y - output
    outgrad = derivatives_sigmoid(output)
    d_output = EO * outgrad

    EH = d_output.dot(wout.T)
    hiddengrad = derivatives_sigmoid(hlayer_act)
    d_hiddenlayer = EH * hiddengrad

    # Updating Weights and Biases
    wout += hlayer_act.T.dot(d_output) * lr
    bout += np.sum(d_output, axis=0, keepdims=True) * lr

    wh += X.T.dot(d_hiddenlayer) * lr
    bh += np.sum(d_hiddenlayer, axis=0, keepdims=True) * lr

    # Print training progress
    print("----------- Epoch", i + 1, "-----------")
    print("Input:\n", X)
    print("Actual Output:\n", y)
    print("Predicted Output:\n", output)
    print("--------------------------------------\n")


----------- Epoch 1 -----------
Input:
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output:
 [[0.92]
 [0.86]
 [0.89]]
Predicted Output:
 [[0.86848656]
 [0.86136496]
 [0.87057937]]
--------------------------------------

----------- Epoch 2 -----------
Input:
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output:
 [[0.92]
 [0.86]
 [0.89]]
Predicted Output:
 [[0.86872369]
 [0.86160407]
 [0.87081383]]
--------------------------------------

----------- Epoch 3 -----------
Input:
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output:
 [[0.92]
 [0.86]
 [0.89]]
Predicted Output:
 [[0.8689577 ]
 [0.86184003]
 [0.8710452 ]]
--------------------------------------

----------- Epoch 4 -----------
Input:
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output:
 [[0.92]
 [0.86]
 [0.89]]
Predicted Output:
 [[0.86918864]
 [0.86207293]
 [0.87127353]]
----